name: Linting & Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os : [ubuntu-latest]
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup ${{ matrix.os }}
      run: |
        sudo apt-get update
        sudo apt install ffmpeg libsm6 libxext6 libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GL
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
        poetry add pylint-exit
    - name: Analysing the code with Ruff
      run: |
        poetry run ruff ./joystick_diagrams ./tests
    - name: Run tests
      run: poetry run pytest --cov-report=term-missing --cov=joystick_diagrams ./tests --cov-report=xml
    - name: Run Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
